from django.contrib.postgres import serializers

from notebook.models import Category, Notebook

class CategorySerializer(serializers.ModelSerializer):
    """
    Serializer for the Category model.
    Converts Category instances to JSON and validates incoming data.
    """

    class Meta:
        model = Category
        fields = ('name', 'created_at', 'updated_at')


class NotebookSerializer(serializers.ModelSerializer):
    """
    Serializer for the Notebook model.

    Adds:
    - a computed field (word_count)
    - validation for title and content
    """

    # Computed field that does not exist in the database
    word_count = serializers.SerializerMethodField()

    def get_word_count(self, obj):
        """
        Called automatically by DRF when serializing.
        'obj' is the Notebook instance currently being serialized.
        Returns the number of words in the content.
        """
        return len(obj.content.split())

    def validate_title(self, value):
        """
        Field-level validation for the 'title' field.

        This method is automatically called by DRF when validating
        the 'title' field during create or update operations.
        """
        if len(value) < 3:
            raise serializers.ValidationError(
                "The title must contain at least 3 characters."
            )
        return value

    def validate_content(self, value):
        """
        Field-level validation for the 'content' field.

        Ensures that the notebook content is not empty or composed only
        of whitespace.
        """
        if not value.strip():
            raise serializers.ValidationError(
                "Content cannot be empty."
            )
        return value

    class Meta:
        model = Notebook

        # Fields exposed by the API
        fields = ('title', 'content', 'created_at', 'updated_at', 'word_count')

        # Fields automatically generated by the server
        read_only_fields = ('created_at', 'updated_at', 'word_count')